config/routes.rb
Renegade::Application.routes.draw do
  
	root to: 'home#index'
	
	resources :rooms do
		collection do
			get 'popular(/when/:time)(/where/:location)', action: :popular
		end
		member do
			match 'composer/link', to: 'composer#link', via: :post
			get 'close'
		end
	end
	
	resources :users, except: :new do
		# more here soon
	end
	
	resources :spaces do
		# more here soon
	end
	
	resources :tags, only: :show
	
	resources :items, only: :show do
		resources :comments, only: [:index, :create]
	end
	
	resources :comments, only: [:show, :create] do
		member do
			get 'reply'
		end
	end
	
	resources :users
	resources :notifications, only: :index do
		collection do
			get 'events'
		end
	end
	
	resources :sessions, only: :create
	get '/in' => 'sessions#new'
	post '/in' => 'sessions#create'
	delete '/out' => 'sessions#destroy'
	
	get '/up' => "users#new"
	
end

app/models/comment.rb
class Comment < ActiveRecord::Base
	
	include Users::Relationship
	attr_accessor :comments
	belongs_to :commented, polymorphic: true
	belongs_to :in_reply_to, class_name: "Comment"
	default_scope {order('created_at DESC')}
	
	validates :commented, presence: true
	validates :user, presence: true
	validates :comment, length: { in: 1..250 }
	
end

app/models/concerns/comments/relationship.rb
module Comments
	module Relationship
		extend ActiveSupport::Concern
		included do
			has_many :comments, as: :commented
		end
	end
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
	
	def reply
		@comment = Comment.find(params[:id])
		@parent = @comment.commented
		@child = Comment.new in_reply_to: @comment
		respond_to do |f|
			f.js { render layout: false }
			f.html
		end
	end
	
	def index; @comments = comment_tree(commented.comments); end
	
	def create
		@comment = commented.comments.create comment_params.merge!(user: current_user)
		respond_to do |f|
			f.js { render layout: false }
			f.html
		end
	end
	
	private 
	
		def comment_params
			params.require(:comment).permit(:in_reply_to_id, :comment)
		end
		
		def commented
			params.each do |name, value|
				puts name
				if name =~ /(.+)_id$/
					return $1.classify.constantize.find value
				end
			end
		end
	
end

app/helpers/comment_helper.rb
module CommentHelper
	
	def comment_tree(c)
		c.each do |comment|
			comment.comments = c.keep_if{|c| c.in_reply_to_id == comment.id}
		end
		c.keep_if{|c| c.in_reply_to_id == 0}
	end
	
end

app/views/comments/_comment.haml
%article{data: {comment: comment.id}}
	= simple_format comment.comment
	%aside
		= raw "#{link_to comment.user.username, comment.user} posted this #{link_to time_ago_in_words(comment.created_at), comment} ago (#{link_to 'reply', reply_comment_path(comment), remote: true})"
%section{data: {comment: comment.id}}
	= render comment.comments if comment.comments

app/views/comments/_comments.haml
= render 'comments/form', parent: object, child: Comment.new
%section.comments
	= render comment_tree object.comments

app/views/comments/_form.haml
= form_for [parent, child], remote: true, html: {class: 'comments'} do |f|
	= f.hidden_field :in_reply_to_id
	= f.text_area :comment
	= f.button type: :submit

app/views/comments/create.js.erb
<% if @comment.in_reply_to_id > 0 %>var cmnt = _.$('comments:parent/comments:comment').filter(_.dataAttr('comments:comment', <%= @comment.in_reply_to_id %>)), replies = _.$('comments:parent/comments:replies').filter(_.dataAttr('comments:comment', <%= @comment.in_reply_to_id %>)); cmnt.nextAll(_.e('comments:form')).remove(); parent.add(replies, '<%= escape_javascript(render @comment) %>');<% else %>parent.add(_.$('comments:parent'), '<%= escape_javascript(render @comment) %>');<% end %>

app/views/comments/reply.js.erb
var comment = _.$('comments:parent/comments:comment').filter('[data-comment=<%= @comment.id %>]');
if (!comment.next(_.e('comments:form')).length) comment.after('<%= escape_javascript(render 'form', parent: @parent, child: @child) %>')