config/routes.rb
Renegade::Application.routes.draw do
  
	root to: 'home#index'
	
	resources :rooms do
		collection do
			get 'popular(/when/:time)(/where/:location)', action: :popular
		end
		member do
			match 'composer/link', to: 'composer#link', via: :post
			get 'close'
		end
	end
	
	resources :users, except: :new do
		# more here soon
	end
	
	resources :spaces do
		# more here soon
	end
	
	resources :tags, only: :show
	
	resources :items, only: :show do
		resources :comments, only: [:index, :create]
	end
	
	resources :comments, only: [:show, :create] do
		member do
			get 'reply'
		end
	end
	
	resources :users
	resources :notifications, only: :index do
		collection do
			get 'events'
		end
	end
	
	resources :sessions, only: :create
	get '/in' => 'sessions#new'
	post '/in' => 'sessions#create'
	delete '/out' => 'sessions#destroy'
	
	get '/up' => "users#new"
	
end

app/controllers/composer_controller.rb
class ComposerController < ApplicationController
	
	def link
		@room = Room.unscoped.find_by_slug params[:id]
		@item = @room.items.new item_params.merge!(item: Items::Link.unscoped.find_or_initialize_by(link_params), user: current_user)
		save_and_respond
	end
	
	private
		
		def save_and_respond
			@item.save!
			respond_to do |f|
				f.js { render 'create', layout: false }
				f.html { redirect_to @item }
			end
		end
		
		def item_params
			params.require(:item).permit(:message)
		end
		
		def link_params
			params.require(:item).require(:link).permit(:url)
		end
	
end

app/controllers/items/composer.rb
module Items
	class Composer
		
		attr_accessor :item, :room
		
		def initialize(room)
			self.room = room
			self.item = room.items.new
		end
		
		def link
			#self.item.item = Items::Link.new
			return self.item
		end
		
	end
end

app/views/composer/_composer.haml
%section.composer
	= link_to "New", "#"
	= form_for object, url: composer_link_room_path(object.room), remote: true do |f|
		%section
			= f.fields_for :link do |o|
				= o.text_field :url, placeholder: "http://.."
			= f.text_area :message, placeholder: "Enter a message..."
		= f.button :submit

app/views/composer/create.js.erb
<% unless @item.errors.any? %>
item.create('<%= escape_javascript(render @item) %>');
<% else %>
alert('error.');
<% end %>